-- SQL schema for Desa Jaten Digital (Supabase)

create table public.pengaduan (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  phone text,
  message text,
  status text default 'baru',
  created_at timestamptz default now()
);

create table public.umkm (
  id bigint generated by default as identity primary key,
  name text,
  owner_name text,
  phone text,
  description text,
  category text,
  image_url text,
  created_at timestamptz default now()
);

create table public.program_desa (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  start_date date,
  end_date date,
  created_at timestamptz default now()
);

create table public.surat_requests (
  id bigint generated by default as identity primary key,
  citizen_name text,
  nik text,
  jenis_surat text,
  fields jsonb,
  status text default 'pending',
  pdf_url text,
  created_at timestamptz default now()
);

create table public.faq (
  id bigint generated by default as identity primary key,
  question text,
  answer text,
  created_at timestamptz default now()
);

-- Example RLS policies (enable RLS and create policies as needed)
-- ALTER TABLE public.pengaduan ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "anon_insert_pengaduan" ON public.pengaduan
--   FOR INSERT USING (true) WITH CHECK (true);
